function Landing({ theme, onToggleTheme, onGenerate, onSignIn }) {
  const [intent, setIntent] = React.useState("");
  const [focus, setFocus] = React.useState(false);
  const suggestions = [
    "Grow my founder audience while building in public",
    "Promote my productivity app to remote workers",
    "Build authority as a fractional CMO"
  ];
  const go = () => onGenerate(intent.trim() || suggestions[0]);
  return /* @__PURE__ */ React.createElement("div", { className: "landing" }, /* @__PURE__ */ React.createElement("header", { className: "nav" }, /* @__PURE__ */ React.createElement("div", { className: "container nav-inner" }, /* @__PURE__ */ React.createElement("a", { className: "brand", href: "#top", "aria-label": "ELPROM home" }, /* @__PURE__ */ React.createElement("span", { className: "brand-mark" }, /* @__PURE__ */ React.createElement(Icon, { name: "bolt", size: 16 })), /* @__PURE__ */ React.createElement("span", { className: "brand-name" }, "ELPROM")), /* @__PURE__ */ React.createElement("nav", { className: "nav-links" }, /* @__PURE__ */ React.createElement("a", { href: "#how" }, "How it works"), /* @__PURE__ */ React.createElement("a", { href: "#proof" }, "Proof"), /* @__PURE__ */ React.createElement("a", { href: "#pricing" }, "Pricing")), /* @__PURE__ */ React.createElement("div", { className: "nav-actions" }, /* @__PURE__ */ React.createElement(ThemeToggle, { theme, onToggle: onToggleTheme }), /* @__PURE__ */ React.createElement("button", { className: "nav-signin", onClick: onSignIn }, "Sign in"), /* @__PURE__ */ React.createElement(Button, { size: "sm", onClick: go }, "Generate my week")))), /* @__PURE__ */ React.createElement("section", { className: "hero", id: "top" }, /* @__PURE__ */ React.createElement("div", { className: "aurora" }), /* @__PURE__ */ React.createElement("div", { className: "container hero-grid" }, /* @__PURE__ */ React.createElement("div", { className: "hero-copy", style: { fontFamily: '"Fira Sans"' } }, /* @__PURE__ */ React.createElement("div", { className: "hero-eyebrow" }, /* @__PURE__ */ React.createElement("span", { className: "dot" }), "Start from proven frameworks, never a blank box"), /* @__PURE__ */ React.createElement("h1", { className: "t-display hero-title" }, "Start from", /* @__PURE__ */ React.createElement("br", null), "what works."), /* @__PURE__ */ React.createElement("p", { className: "t-body hero-sub" }, "Type one line. Get a whole week of proven, ready-to-post content \u2014 words ", /* @__PURE__ */ React.createElement("em", null, "and"), " visuals."), /* @__PURE__ */ React.createElement("div", { className: `hero-input ${focus ? "focus" : ""}` }, /* @__PURE__ */ React.createElement(Icon, { name: "sparkle", size: 18, className: "hero-input-icon" }), /* @__PURE__ */ React.createElement(
    "input",
    {
      className: "hero-input-field",
      placeholder: "What do you want to be known for?",
      value: intent,
      onChange: (e) => setIntent(e.target.value),
      onFocus: () => setFocus(true),
      onBlur: () => setFocus(false),
      onKeyDown: (e) => {
        if (e.key === "Enter") go();
      },
      "aria-label": "Describe your content goal"
    }
  ), /* @__PURE__ */ React.createElement(Button, { onClick: go, iconRight: "arrowRight", className: "hero-input-cta" }, "Generate my week")), /* @__PURE__ */ React.createElement("div", { className: "hero-suggest" }, /* @__PURE__ */ React.createElement("span", { className: "text-3 t-small" }, "Try:"), /* @__PURE__ */ React.createElement("div", { className: "chip-row" }, suggestions.map(
    (s) => /* @__PURE__ */ React.createElement("button", { key: s, className: "chip", onClick: () => setIntent(s) }, s)
  ))), /* @__PURE__ */ React.createElement("div", { className: "trust-row" }, /* @__PURE__ */ React.createElement("span", { className: "trust" }, /* @__PURE__ */ React.createElement(Icon, { name: "check", size: 14 }), "Free to start"), /* @__PURE__ */ React.createElement("span", { className: "trust" }, /* @__PURE__ */ React.createElement(Icon, { name: "check", size: 14 }), "No login required"), /* @__PURE__ */ React.createElement("span", { className: "trust" }, /* @__PURE__ */ React.createElement(Icon, { name: "check", size: 14 }), "650K proven frameworks"))), /* @__PURE__ */ React.createElement("div", { className: "hero-right" }, /* @__PURE__ */ React.createElement(HeroDevice, null), /* @__PURE__ */ React.createElement("div", { className: "float-card fc-1 card-glass" }, /* @__PURE__ */ React.createElement(FormatChip, { type: "Reel" }), /* @__PURE__ */ React.createElement("div", { className: "fc-text" }, "Hook scored ", /* @__PURE__ */ React.createElement("b", null, "92/100"))), /* @__PURE__ */ React.createElement("div", { className: "float-card fc-2 card-glass" }, /* @__PURE__ */ React.createElement("div", { className: "avatar", style: { width: 28, height: 28, fontSize: 12 } }, "A"), /* @__PURE__ */ React.createElement("div", { className: "fc-text" }, "Posted to ", /* @__PURE__ */ React.createElement("b", null, "@buildwithava")))))), /* @__PURE__ */ React.createElement("section", { className: "section how", id: "how" }, /* @__PURE__ */ React.createElement("div", { className: "container" }, /* @__PURE__ */ React.createElement(Rise, { className: "sec-head" }, /* @__PURE__ */ React.createElement("span", { className: "t-label text-accent" }, "How it works"), /* @__PURE__ */ React.createElement("h2", { className: "t-h1" }, "From one line to a finished week.")), /* @__PURE__ */ React.createElement("div", { className: "how-grid" }, [
    { n: "01", icon: "edit", t: "Type one line of intent", d: "Your niche, your goal, your platform. One sentence is all ELPROM needs to begin." },
    { n: "02", icon: "sparkle", t: "We start from what works", d: "Every post is built on a proven framework from a library of 650K \u2014 never a blank box." },
    { n: "03", icon: "calendar", t: "Get a ready-to-post week", d: "Seven days of hooks, captions, hashtags and designed graphics. Copy, download, done." }
  ].map(
    (s, i) => /* @__PURE__ */ React.createElement(Rise, { key: s.n, delay: i * 90, className: "how-card card card-hover" }, /* @__PURE__ */ React.createElement("div", { className: "how-num t-mono-stat text-3" }, s.n), /* @__PURE__ */ React.createElement("div", { className: "how-icon" }, /* @__PURE__ */ React.createElement(Icon, { name: s.icon, size: 20 })), /* @__PURE__ */ React.createElement("h3", { className: "t-h3" }, s.t), /* @__PURE__ */ React.createElement("p", { className: "t-small text-2" }, s.d))
  )))), /* @__PURE__ */ React.createElement("section", { className: "section proof", id: "proof" }, /* @__PURE__ */ React.createElement("div", { className: "container" }, /* @__PURE__ */ React.createElement(Rise, { className: "stat-strip card-glass" }, [
    { v: "650K", l: "Proven frameworks" },
    { v: "~8s", l: "To a full week" },
    { v: "7 days", l: "Finished every run" },
    { v: "4.3\xD7", l: "More consistent posting" }
  ].map(
    (s) => /* @__PURE__ */ React.createElement("div", { className: "stat", key: s.l }, /* @__PURE__ */ React.createElement("div", { className: "t-mono-stat" }, s.v), /* @__PURE__ */ React.createElement("div", { className: "t-small text-2" }, s.l))
  )), /* @__PURE__ */ React.createElement("div", { className: "quotes" }, [
    { q: "I went from posting twice a month to every single day. The frameworks do the thinking \u2014 I just hit publish.", n: "Ava Mirza", r: "Founder, Loomly", a: "A" },
    { q: "It feels like a ghostwriter who already studied my niche. The Monday carousel alone got us 40 demo signups.", n: "Devin Okafor", r: "Building Hopscotch", a: "D" },
    { q: "The 7-day view is the unlock. I can see my whole week of content land in seconds and edit from there.", n: "Priya Sundar", r: "Solo SaaS founder", a: "P" }
  ].map(
    (c, i) => /* @__PURE__ */ React.createElement(Rise, { key: c.n, delay: i * 80, className: "quote card card-hover" }, /* @__PURE__ */ React.createElement("p", { className: "t-body quote-text" }, "\u201C", c.q, "\u201D"), /* @__PURE__ */ React.createElement("div", { className: "quote-by" }, /* @__PURE__ */ React.createElement("div", { className: "avatar" }, c.a), /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("div", { className: "t-small", style: { fontWeight: 640 } }, c.n), /* @__PURE__ */ React.createElement("div", { className: "t-small text-3" }, c.r))))
  )))), /* @__PURE__ */ React.createElement("section", { className: "section pricing", id: "pricing" }, /* @__PURE__ */ React.createElement("div", { className: "container" }, /* @__PURE__ */ React.createElement(Rise, { className: "sec-head center" }, /* @__PURE__ */ React.createElement("span", { className: "t-label text-accent" }, "Pricing"), /* @__PURE__ */ React.createElement("h2", { className: "t-h1" }, "Start free. Upgrade when it\u2019s working.")), /* @__PURE__ */ React.createElement("div", { className: "plans" }, /* @__PURE__ */ React.createElement(Rise, { className: "plan card" }, /* @__PURE__ */ React.createElement("div", { className: "plan-head" }, /* @__PURE__ */ React.createElement("span", { className: "t-h3" }, "Free"), /* @__PURE__ */ React.createElement("div", { className: "plan-price" }, /* @__PURE__ */ React.createElement("span", { className: "t-mono-stat" }, "$0")), /* @__PURE__ */ React.createElement("p", { className: "t-small text-2" }, "Everything you need to feel the magic.")), /* @__PURE__ */ React.createElement("ul", { className: "plan-list" }, ["1 calendar per week", "Hooks, captions & hashtags", "Designed graphics", "\u201COpen in AI\u201D offload", "\u201CMade with ELPROM\u201D watermark"].map(
    (f) => /* @__PURE__ */ React.createElement("li", { key: f }, /* @__PURE__ */ React.createElement(Icon, { name: "check", size: 16, className: "text-accent" }), f)
  )), /* @__PURE__ */ React.createElement(Button, { variant: "ghost", onClick: () => onGenerate(suggestions[0]), className: "plan-cta" }, "Start free")), /* @__PURE__ */ React.createElement(Rise, { delay: 80, className: "plan plan-pro card" }, /* @__PURE__ */ React.createElement("div", { className: "plan-glow" }), /* @__PURE__ */ React.createElement("div", { className: "plan-head" }, /* @__PURE__ */ React.createElement("div", { className: "row gap-8" }, /* @__PURE__ */ React.createElement("span", { className: "t-h3" }, "Pro"), /* @__PURE__ */ React.createElement("span", { className: "pro-badge" }, /* @__PURE__ */ React.createElement(Icon, { name: "bolt", size: 11 }), "Most popular")), /* @__PURE__ */ React.createElement("div", { className: "plan-price" }, /* @__PURE__ */ React.createElement("span", { className: "t-mono-stat" }, "$25"), /* @__PURE__ */ React.createElement("span", { className: "text-2" }, "/mo")), /* @__PURE__ */ React.createElement("p", { className: "t-small text-2" }, "For creators who post to grow.")), /* @__PURE__ */ React.createElement("ul", { className: "plan-list" }, ["Unlimited calendars", "No watermark", "Your brand voice", "Scheduling reminders", "AI-generated images", "Priority generation"].map(
    (f) => /* @__PURE__ */ React.createElement("li", { key: f }, /* @__PURE__ */ React.createElement(Icon, { name: "check", size: 16, className: "text-accent" }), f)
  )), /* @__PURE__ */ React.createElement(Button, { onClick: onSignIn, className: "plan-cta" }, "Go Pro"), /* @__PURE__ */ React.createElement("div", { className: "plan-foot text-3 t-small" }, "Cancel anytime."))))), /* @__PURE__ */ React.createElement("section", { className: "final-cta" }, /* @__PURE__ */ React.createElement("div", { className: "aurora" }), /* @__PURE__ */ React.createElement("div", { className: "container final-inner" }, /* @__PURE__ */ React.createElement("h2", { className: "t-h1" }, "A week of your content,", /* @__PURE__ */ React.createElement("br", null), "in the next eight seconds."), /* @__PURE__ */ React.createElement(Button, { size: "lg", onClick: go, iconRight: "arrowRight" }, "Generate my week"))), /* @__PURE__ */ React.createElement("footer", { className: "footer" }, /* @__PURE__ */ React.createElement("div", { className: "container footer-inner" }, /* @__PURE__ */ React.createElement("div", { className: "brand" }, /* @__PURE__ */ React.createElement("span", { className: "brand-mark" }, /* @__PURE__ */ React.createElement(Icon, { name: "bolt", size: 16 })), /* @__PURE__ */ React.createElement("span", { className: "brand-name" }, "ELPROM")), /* @__PURE__ */ React.createElement("p", { className: "t-small text-3" }, "Start from what works."), /* @__PURE__ */ React.createElement("div", { className: "footer-links" }, /* @__PURE__ */ React.createElement("a", { href: "#how" }, "Product"), /* @__PURE__ */ React.createElement("a", { href: "#pricing" }, "Pricing"), /* @__PURE__ */ React.createElement("a", { href: "#proof" }, "Stories"), /* @__PURE__ */ React.createElement("a", { href: "#top" }, "Privacy")))));
}
window.Landing = Landing;
